"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuOjix65Lrz02YrQ2ou37Uc2Q-11LGV7
"""

#-----Caso de uso 1-------
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.impute import SimpleImputer

def generar_caso_de_uso_detectar_anomalias_industrialesdf, contaminacion=0.05):
    """
    Detecta registros atípicos en un DataFrame utilizando Isolation Forest.

    Argumentos:
    df (pd.DataFrame): DataFrame con variables numéricas.
    contaminacion (float): Proporción esperada de anomalías en el conjunto.

    Retorno:
    numpy.ndarray: Array con 1 (normal) y -1 (anomalía).
    """
    # 1. Aseguramos que solo trabajamos con datos numéricos
    datos_numericos = df.select_dtypes(include=[np.number])

    # 2. Manejo de valores nulos (Imputación por mediana)
    imputador = SimpleImputer(strategy='median')
    datos_limpios = imputador.fit_transform(datos_numericos)

    # 3. Configuración y entrenamiento del modelo Isolation Forest
    # random_state asegura que el resultado sea reproducible
    modelo = IsolationForest(contamination=contaminacion, random_state=42)

    # 4. Ajuste y predicción
    # El método fit_predict devuelve 1 para inliers y -1 para outliers
    predicciones = modelo.fit_predict(datos_limpios)

    return predicciones

# --- Caso de Uso: Monitoreo de Flota de Camiones ---

# Creación de un dataset sintético
data = {
    'id_camion': range(1, 11),
    'velocidad_promedio_kmh': [80, 82, 79, 85, 20, 81, 83, 78, 90, 15],
    'consumo_combustible_gals': [10, 11, 10.5, 12, 45, 10.8, 11.2, 9.5, 13, 50]
}

df_logistica = pd.DataFrame(data)

# Ejecución de la función
# Buscamos el 20% de anomalías (2 de los 10 registros en este ejemplo)
resultados = detectar_anomalias_industriales(df_logistica[['velocidad_promedio_kmh', 'consumo_combustible_gals']],
                                             contaminacion=0.2)

# Añadir resultados al DataFrame original para visualización
df_logistica['estado'] = np.where(resultados == 1, 'Normal', 'Anomalía')

print("Análisis de la Flota:")
print(df_logistica)

# Ejemplo de cómo filtrar las anomalías detectadas
anomalias_detectadas = df_logistica[df_logistica['estado'] == 'Anomalía']
print("\nAlertas para revisión mecánica o de seguridad:")
print(anomalias_detectadas)
