# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGEiPUkXdTS5QJWULnZlrTgxNIMFcnoB
"""

#-------Caso de uso 2------
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

def comprimir_dimensiones_por_varianza(X, umbral_varianza=0.95):
    """
    Reduce la dimensionalidad de un dataset conservando un porcentaje
    específico de la varianza de los datos.
    """
    # 1. Es fundamental escalar los datos antes de aplicar PCA
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # 2. Inicializamos PCA con el umbral de varianza deseado
    # Al pasar un float entre 0 y 1, sklearn selecciona automáticamente
    # el número de componentes necesarios.
    pca = PCA(n_components=umbral_varianza)

    # 3. Ajustamos y transformamos los datos
    X_reducido = pca.fit_transform(X_scaled)

    # 4. Retornamos el array de numpy
    return X_reducido

# --- Ejemplo de aplicación: Dataset de Sensores Biométricos ---

# Creamos un dataset ficticio con 100 muestras y 50 columnas.
# Muchas columnas serán redundantes (multiplicaciones de otras).
np.random.seed(42)
base_data = np.random.rand(100, 5) # Solo 5 variables reales
redundant_data = np.dot(base_data, np.random.rand(5, 45)) # Creamos 45 columnas dependientes
full_data = np.hstack([base_data, redundant_data])

df_biometrico = pd.DataFrame(full_data, columns=[f'Sensor_{i}' for i in range(50)])

print(f"Dimensiones originales: {df_biometrico.shape}")

# Ejecutamos la función para conservar el 90% de la información
matriz_reducida = comprimir_dimensiones_por_varianza(df_biometrico, umbral_varianza=0.90)

print(f"Dimensiones después de la compresión: {matriz_reducida.shape}")
print(f"Tipo de objeto devuelto: {type(matriz_reducida)}")
print("\nPrimeras 2 filas del array reducido:")
print(matriz_reducida[:2])