# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151bSqfDPiy9fSKkIMyaA7MKPwWcA-FbV
"""

#---- Caso de uso 4---------
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor

def predecir_emisiones_co2(X_train, y_train, X_test):
    """
    Entrena un regresor de bosque aleatorio para estimar valores
    continuos de emisiones de carbono.
    """
    # 1. Instanciar el modelo de regresión
    # Usamos n_estimators=100 para un equilibrio entre precisión y velocidad
    modelo = RandomForestRegressor(n_estimators=100, random_state=42)

    # 2. Entrenar el modelo con los datos históricos (X_train, y_train)
    modelo.fit(X_train, y_train)

    # 3. Realizar las predicciones sobre el conjunto nuevo (X_test)
    predicciones = modelo.predict(X_test)

    # 4. Asegurar que el retorno sea un array de NumPy
    return np.array(predicciones)

# --- Ejemplo de aplicación: Inventario Ambiental ---

# Datos históricos de 5 fábricas (Consumo KWh, Superficie m2, Empleados)
data_historica = {
    'consumo_kwh': [5000, 12000, 8000, 20000, 15000],
    'superficie_m2': [1000, 2500, 1800, 4000, 3200],
    'empleados': [50, 120, 80, 200, 150]
}
emisiones_reales = [150.5, 380.2, 240.0, 610.8, 450.3]

X_entrenamiento = pd.DataFrame(data_historica)
y_entrenamiento = np.array(emisiones_reales)

# Nuevas fábricas que acaban de abrir (no conocemos sus emisiones)
data_nuevas = {
    'consumo_kwh': [7000, 18000, 9500],
    'superficie_m2': [1500, 3500, 2000],
    'empleados': [70, 180, 90]
}
X_nuevas = pd.DataFrame(data_nuevas)

# Ejecución de la función
emisiones_estimadas = predecir_emisiones_co2(X_entrenamiento, y_entrenamiento, X_nuevas)

print("Estimaciones de CO2 para las nuevas plantas (Toneladas):")
print(emisiones_estimadas)
print(f"Tipo de objeto: {type(emisiones_estimadas)}")

# Validación rápida
for i, est in enumerate(emisiones_estimadas):
    print(f"Fábrica nueva {i+1}: {est:.2f} toneladas de CO2 proyectadas.")