# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSpZyYsEwanXKcT1k-veK28KYTgaISAS
"""

#------ Caso de uso 3------
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

def clasificar_tickets_soporte(textos, etiquetas, nuevo_mensaje):
    """
    Entrena un modelo de clasificación de texto y predice la categoría
    de un nuevo mensaje utilizando TF-IDF y Naive Bayes.
    """
    # 1. Convertimos la lista de textos a un DataFrame para manejo consistente
    df = pd.DataFrame({'mensaje': textos})

    # 2. Vectorización TF-IDF: convierte texto en valores numéricos
    # basados en la importancia de las palabras.
    vectorizador = TfidfVectorizer(stop_words=None) # Podría usarse 'spanish' si hay nltk
    X = vectorizador.fit_transform(df['mensaje'])

    # 3. Entrenamiento del modelo Naive Bayes (ideal para texto)
    modelo = MultinomialNB()
    modelo.fit(X, etiquetas)

    # 4. Transformar el nuevo mensaje usando el MISMO vectorizador
    X_nuevo = vectorizador.transform([nuevo_mensaje])

    # 5. Realizar la predicción
    prediccion = modelo.predict(X_nuevo)

    # Retornamos el array de numpy con la predicción
    return prediccion

# --- Ejemplo de aplicación: Clasificación de Intenciones ---

mensajes_entrenamiento = [
    "Mi cuenta fue hackeada y perdí mi acceso",
    "¿A qué hora cierran la tienda el sábado?",
    "Alguien entró en mi perfil sin permiso",
    "¿Cuál es el precio del servicio premium?",
    "Urgente: mi información personal está expuesta",
    "¿Tienen sucursales en Medellín?"
]

categorias = [
    "Seguridad", "Información", "Seguridad",
    "Información", "Seguridad", "Información"
]

# Mensaje que el sistema nunca ha visto
nuevo_ticket = "Me preocupa que mi contraseña fue robada"

# Ejecución de la función
resultado_array = clasificar_tickets_soporte(mensajes_entrenamiento, categorias, nuevo_ticket)

print(f"Nuevo mensaje: '{nuevo_ticket}'")
print(f"Predicción del sistema: {resultado_array}")
print(f"Tipo de objeto devuelto: {type(resultado_array)}")

# Verificación de lógica
if resultado_array[0] == "Seguridad":
    print("Acción: Notificar al equipo de ciberseguridad inmediatamente.")
else:
    print("Acción: Enviar respuesta automática con horarios de atención.")